// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-v8HrhdF50mO1l2PV6FskAB1qVfLXEEY',
    appId: '1:629559071896:web:973e545113eba9fa9baced',
    messagingSenderId: '629559071896',
    projectId: 'eventos-en-hoteles-aspl',
    authDomain: 'eventos-en-hoteles-aspl.firebaseapp.com',
    storageBucket: 'eventos-en-hoteles-aspl.firebasestorage.app',
    measurementId: 'G-4P81G4GYEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLRQox1yk1SxXbIKrLF6GkfA19Xw0YIc',
    appId: '1:629559071896:android:c51acb888a8edd629baced',
    messagingSenderId: '629559071896',
    projectId: 'eventos-en-hoteles-aspl',
    storageBucket: 'eventos-en-hoteles-aspl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-0Dxbwaj66VPZxJs6zOocsagRzDdc_0',
    appId: '1:629559071896:ios:d3bd64fbd29dd10f9baced',
    messagingSenderId: '629559071896',
    projectId: 'eventos-en-hoteles-aspl',
    storageBucket: 'eventos-en-hoteles-aspl.firebasestorage.app',
    iosBundleId: 'com.example.followroomFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX-0Dxbwaj66VPZxJs6zOocsagRzDdc_0',
    appId: '1:629559071896:ios:d3bd64fbd29dd10f9baced',
    messagingSenderId: '629559071896',
    projectId: 'eventos-en-hoteles-aspl',
    storageBucket: 'eventos-en-hoteles-aspl.firebasestorage.app',
    iosBundleId: 'com.example.followroomFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-v8HrhdF50mO1l2PV6FskAB1qVfLXEEY',
    appId: '1:629559071896:web:4d181a30a7f3b8b89baced',
    messagingSenderId: '629559071896',
    projectId: 'eventos-en-hoteles-aspl',
    authDomain: 'eventos-en-hoteles-aspl.firebaseapp.com',
    storageBucket: 'eventos-en-hoteles-aspl.firebasestorage.app',
    measurementId: 'G-7TTQVDY4SY',
  );
}
